#!/bin/bash

###
# Cleans target of all FLAC files that are owned by IMAGEID that exist in TARGET directory 
###

clean_target() {
    local TARGET="${1}"
    local IMAGEID="${2}"
    local MANIFEST="${3}"

    for old_file in $(grep ${IMAGEID} ${MANIFEST} | cut -d'=' -f1); do
        rm ${TARGET}/${old_file}
    done
    sed -i "/${IMAGEID}/d" ${MANIFEST}
    find ${TARGET}/* -empty -type d -delete >/dev/null 2>&1
}

