#!/bin/bash

# doc cmd_import {
#
# DESCRIPTION
#   cmd_import - Wrapper for import functions
#
# USAGE
#   cmd_import <source> </path/to/git/dir> </path/to/import/dir> [<...>]
#
# SOURCES
#   images      Import images into git repository. Image file must be accompanied
#               by cue sheet of the same name in folder. Will also import any 
#               accompanying .log, .accurip, .jpg file barring they share the same
#               name.
#
#   tracks      Import tracks, or archive containing tracks, into git directory
#
# DEPENDENCIES src/import_tracks src/import_images
#
# }

cmd_import() {
    local CMD="${1}"
    local GIT_DIR="${2}"; shift 2
    local dirList=(${@})

    eval import_${CMD} "${GIT_DIR}" ${@}
}
