#!/bin/bash

# doc cmd_include {
#
# DESCRIPTION
#   cmd_include - Include track that matches CONDITION in DB_FILE
#
# USAGE
#   cmd_include </path/to/dir/dir> </path/to/target> </path/to/db_file> <condition_1> <condition_2> <...>
#
# CONDITIONS
#   CONDITIONS are defined using the following format:
#       <metadata field>=<value>
#   The metadata field can be anything that can be injected as metadata in a Vorbis or id3tag. 
#
# }

cmd_include() {
    local GIT_DIR="${1}"
    local TARGET="${2}"
    local DB_FILE="${TARGET}/${_OPT_DB_FILE}"; shift 2
    local conditionList=("${@}")
    [[ ! -f "${DB_FILE}" ]] && return 1
    [[ ! -f "${GIT_DIR}/.git" ]] && return 2

    for condition in ${conditionList[@]}; do
        _msg EXEC "Including all tracks that match the following condition: ${condition}"
        db_set ${GIT_DIR} ${DB_FILE} true "${condition}"
        [[ $? -ne 0 ]] && { _msg WARN; } || { _msg OK; }
    done
    local imageidList=($(awk 'BEGIN{FS="\t"}{if($1=="true"){print $2}}' ${DB_FILE} | awk '!seen[$0]++'))
    local DU="$(print_imageid_du ${GIT_DIR} ${imageidList[@]})"
    _msg ECHO "Current estimated disk usage: ${DU} bytes"

}
