#!/bin/bash

###
# Command initializes TARGET directory by creating OPT_FILE_MANIFEST and OPT_FILE_EXCLUDE
# OPT_FILE_COMMIT
###

cmd_init() {
    local TARGET="${1}"
    local MANIFEST="${TARGET}/${MANIFEST}"
    local LAST_COMMIT="${TARGET}/${LAST_COMMIT}"
    local EXCLUDE="${TARGET}/${EXCLUDE}"

    [[ -z "$(ls -A "${TARGET}")" ]] || return 1
    touch "${MANIFEST}"
    touch "${EXCLUDE}"
    echo "COMMIT=$(git rev-list HEAD | tail -n 1)" > ${LAST_COMMIT}
    [[ $? -eq 0 ]] && return 0 || return 2
}

