#!/bin/bash

# doc cmd_import_tracks {
#
# DESCRIPTION
#   cmd_import_tracks - Wrapper for import_tracks
#
# USAGE
#   cmd_import_tracks </path/to/work/dir> <subpath/to/album>
#
# }

cmd_import_tracks {
    local ROOT="${1}"; shift 1
    local dirList=("${@}")
    for dir in ${dirList[@]}; do
        folderList=($(find ${ROOT}/${dir} -name '*cover*' -printf '%h\n' | awk '!seen[$0]++' | sed "s|${ROOT}/||g"))
        for folder in ${folderList[@]}; do
            gen ${ROOT} "${folder}"
        done
    done
}
