#!/bin/bash

# doc cmd_import_images {
#
# DESCRIPTION
#   cmd_import_images - Imports CD images into GIT_DIR
#
# USAGE
#   cmd_import_images </path/to/image/folder> [<...>]
#
# DEPENDENCIES src/import_images
#
# }

cmd_import_images() {
    local GIT_DIR="${1}"; shift
    local dirList=("${@}")

    for dir in ${dirList[@]}; do
        folderList=($(find "${dir}" -name '*.cue' -printf '%h\n' | awk '!seen[$0]++'))
        for folder in ${folderList[@]}; do
            import_images "${GIT_DIR}" "${folder}"
        done
    done
}
