#!/bin/bash

# doc export_rm {
# 
# DESCRIPTION
#   export_rm - Removes TRACKIDs from TARGET
#
# USAGE
#   export_rm </path/to/target> </path/to/db/file> <TRACKID>
#
# DEPENDENCIES bunc/src/* src/print_present_path
#
# }

export_rm() {
    ## Argument parsing
    local TARGET="${1}"
    local DB_FILE="${2}"
    local IMAGEID=$(awk 'BEGIN{FS="--"}{print $1"--"$2}' <<< ${3})
    local TRACKID=$(awk 'BEGIN{FS="--"}{print $3}' <<< ${3})

    ## Removes trackids from TARGET
    _msg EXEC "Removing ${TRACKID} from ${TARGET})"
    local pathList=($( awk -v trackid=${TRACKID} 'BEGIN{FS="\t"}{if($3==trackid && $4!="null"){print $4}})'))
    if [[ ${#pathList[@]} -eq 1 ]]; then
        rm "${TARGET}/$(print_present_path "${DB_FILE}" ${IMAGEID} ${TRACKID})" >${STDERR} 2>&1
    else
        echo "Detected multiple instances of ${TRACKID} with same paths, will not delete" > ${STDERR}
        _msg WARN
    fi

    [[ $? -eq 0 ]] && { _msg OK; gawk -i inplace -v imageid=${IMAGEID} -v trackid=${TRACKID} -v value=null  'BEGIN{FS="\t";OFS="\t"}{if(($3==trackid && $2==imageid) && $1=="null"){$4=value}{print $0}}' ${DB_FILE}; return 0; } || { _msg WARN; return 1; } 
}

