#!/bin/bash

# doc export_mv {
# 
# DESCRIPTION
#   export_mv - Renames output files from export_gen to associated TRACKID
#
# USAGE
#   export_mv </path/to/git/dir> <IMAGEID.
# }

export_mv() {
    local GITDIR="${1}"
    local IMAGEID="${2}"
    
    # Generated trackidList to know what id to assign to each file
    local trackidList=$(awk -v field="\"TRACKID\"" 'BEGIN{RS="[,]?\n";FS=" : "}{if($1~field){print $2}}' "${GITDIR}/${IMAGEID}.tags" | tr -d '"')

    # Then renames the ouput files to TRACKID
    local COUNT=1
    for trackid in ${trackidList[@]}; do
        mv "${GITDIR}/$(printf 'split-track%02d.flac' ${COUNT})" "${GITDIR}/${IMAGEID}-${trackid}.flac"
        local COUNT=$(( ${COUNT} + 1 ))
    done
    return 0
}
    
