#!/bin/bash

# doc gen_image {
#
# DESCRIPTION
#   gen_image - Generates image from list of lossless audio files
#
# USAGE
#   gen_image </path/to/output/dir> <file_1> [<file_1>] [<...>]
#
# DEPENDENCIES src/med_convert
#
# }

gen_image() {
    local TARGET_DIR="${1}"; shift
    local fileList=("${@}")
    if [[ ${#fileList[@]} -eq 1 ]]; then
        cat ${fileList[@]} > joined.flac
    else
        shntool join -O always ${fileList[@]} -d "${TARGET_DIR}" -o flac -q
        if [[ $? -ne 0 ]]; then
            med_convert wav ${fileList[@]}
            [[ $? -ne 0 ]] && return 1
            echo ${fileList[@]}
            fileList=($(printf '%s\n' ${fileList[@]} | sed 's|flac|wav|'))
            echo ${fileList[@]}
            shntool join -O always ${fileList[@]} -d "${TARGET_DIR}" -o flac -q
            [[ $? -ne 0 ]] && return 1
            return 2
        fi
    fi
    metaflac --remove-all --dont-use-padding "${TARGET_DIR}/joined.flac"
    return 0
}

