#!/bin/bash

# doc gen_cue {
#
# DESCRIPTION
#   gen_cue - Generates cue file from print_meta function
#
# USAGE
#   gen_cue <print_meta_flac-output-track-1> <print_meta_flac-output-track-2> <...>
#
# DEPENDENCIES src/print_cue_breaklist
#
# }

gen_cue() {
    local TARGET_DIR="${1}"; shift
    local metadata_trackList=(${@})

    # Generates tag arrays
    local COUNT=0
    for metadata_track in ${metadata_trackList[@]}; do
        local dateList[${COUNT}]=$(awk -v tag="DATE" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local composerList[${COUNT}]=$(awk -v tag="COMPOSER" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local conductorList[${COUNT}]=$(awk -v tag="CONDUCTOR" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local orchestraList[${COUNT}]=$(awk -v tag="ORCHESTRA" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local artistList[${COUNT}]=$(awk -v tag="ARTIST" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local albumList[${COUNT}]=$(awk -v tag="ALBUM" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local imageidList[${COUNT}]=$(awk -v tag="IMAGEID" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local titleList[${COUNT}]=$(awk -v tag="TITLE" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local isrcList[${COUNT}]=$(awk -v tag="ISRC" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local commentList[${COUNT}]=$(awk -v tag="COMMENT" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local albumList[${COUNT}]=$(awk -v tag="ALBUM" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})
        local COUNT=$(( ${COUNT} + 1 ))
    done
    local tagList=($( sed -e 's| ; ||g' -e 's|; ;||' <<< ${tagList[@]} |  tr ';' \\n | awk '!seen[$0]++' ))
    
    # Generates breaklist
    local fileList=($(find "${TARGET_DIR}" -name '*.flac' -printf '%p\t'))
    local breakList=($(print_cue_breaklist ${fileList[@]}))

    [[ ! -z "${dateList}" ]] && echo "REM DATE ${dateList}"
    [[ ! -z "${composerList}" ]] && echo "PERFORMER \"${composerList}\""
    [[ ! -z "${conductorList}" ]] && echo "REM CONDUCTOR \"${conductorList}\""
    [[ ! -z "${orchestraList}" ]] && echo "REM ORCHESTRA \"${orchestraList}\""
    [[ ! -z "${commentList}" ]] && echo "REM COMMENT \"${commentList}\""
    [[ ! -z "${artistList}" ]] && echo "PERFORMER \"${artistList}\""
    [[ ! -z "${albumList}" ]] && echo "TITLE \"${albumList}\""
    echo "FILE \"${imageidList}.flac\" WAVE"
    local COUNT=0
    while [[ ${COUNT} -lt ${#breakList[@]} ]]; do
        [[ ${COUNT} -le 8 ]] && local TRACK_NO="0$(( ${COUNT} + 1 ))" || local TRACK_NO="$(( ${COUNT} + 1 ))"
        echo "  TRACK ${TRACK_NO} AUDIO" 
        echo "    TITLE \"${titleList[${COUNT}]}\""
        [[ ! -z "${isrcList[${COUNT}]}" ]] && echo "    ISRC ${isrcList[${COUNT}]}"
        echo "    INDEX 01 ${breakList[${COUNT}]}"
        local COUNT=$(( ${COUNT} + 1 ))
    done
    return 0
}

