#!/bin/bash

# doc gen_image {
#
# DESCRIPTION
#   gen_image - Generates image from list of lossless audio files
#
# USAGE
#   gen_image <file_1> [<file_1>] [<...>]
#
# }

gen_image() {
    local fileList=("${@}")
    if [[ ${#fileList[@]} -eq 1 ]]; then
        cat ${fileList[@]} > joined.flac
    else
        shntool join -O always ${fileList[@]} -o flac
        if [[ $? -ne 0 ]]; then
            med_convert wav ${fileList[@]}
            [[ $? -ne 0 ]] && { echo "Image generation failed with fatal errors"; return 1; }
            echo ${fileList[@]}
            fileList=($(printf '%s\n' ${fileList[@]} | sed 's|flac|wav|'))
            echo ${fileList[@]}
            shntool join -O always ${fileList[@]} -o flac
            [[ $? -ne 0 ]] && { echo "Image generation failed with fatal errors"; return 1; }
            echo "Image generated with non-fatal error"; return 2
        fi
    fi
    echo "Image generated with no errors"; return 0
}

