#!/bin/bash

# doc gen_trackid {
#
# DESCRIPTION
#   gen_trackid - Generates list of TRACKIDs for specified FLAC file
#
# USAGE
#   gen_trackid </path/to/flac/file> </path/to/cue/fule>
#
# DEPENDENCIES src/deploy_split
#
# }

gen_trackid() {
    FLAC="${1}"
    CUE="${2}"

    deploy_split ${FLAC} ${CUE} >/dev/null 2>&1
    local TOTALTRACKS="$(grep -e "TRACK [0-9][0-9] AUDIO" "${CUE}" | wc -l)"

    local COUNT=1
    while [[ ${COUNT} -le ${TOTALTRACKS} ]]; do
        local TRACKID="$(metaflac --list --block-number=0 $(printf "split-track%02d.flac" ${COUNT}) | awk 'BEGIN{FS=": "}{if($1=="  MD5 signature") {print $2}}')"
        printf "%s\t" ${TRACKID}
        rm $(printf "split-track%02d.flac" ${COUNT})
        local COUNT=$(( ${COUNT} + 1 ))
    done
}

