#!/bin/bash

# doc gen_cover {
#
# DESCRIPTION
#   gen_small_cover - Generate small version of cover image 
#
# USAGE
#   gen_small_cover </path/to/image>
#
# }

gen_small_cover() {
    local COVER="${1}"
    convert "${COVER}" -resize 480x480^ -gravity center -extent 480x480x0x0 -
    local EXIT=$?
    [[ ${EXIT} -ne 0 ]] && return 1
    return 0
}

