#!/bin/bash

# doc gen_cue {
#
# DESCRIPTION
#   gen_cue - Generates cue file from print_meta function
#
# USAGE
#   gen_cue <print_meta_flac-output-track-1> <print_meta_flac-output-track-2> <...>
#
# DEPENDENCIES src/print_cue_breaklist
#
# }

gen_cue() {
    local TARGET_DIR="${1}"; shift
    local metadata_trackList=(${@})

    # Generates list of tags to be parsed 
    local COUNT=0
    for metadata_track in ${metadata_trackList[@]}; do
        local tagList[${COUNT}]=$(awk 'BEGIN{RS=";";FS="=";ORS=";";}{print $1}' <<< ${metadata_track})
        local COUNT=$(( ${COUNT} + 1 ))
    done
    local tagList=($( sed -e 's| ; ||g' -e 's|; ;||' <<< ${tagList[@]} |  tr ';' \\n | awk '!seen[$0]++' ))
    
    # Generates breaklist
    local fileList=($(find "${TARGET_DIR}" -name '*.flac' -print '%p\t'))
    local breakList=($(print_cue_breaklist ${fileList[@]}))

    # Parses metadata
    local COUNT=0
    for tag in ${tagList[@]}; do
        local TAG_VALUE="$(awk -v tag="${tag}" 'BEGIN{RS=";";FS="=";}{if($1==tag){print $2}}' <<< ${metadata_track})"
        eval local ${tag}List[${COUNT}]="${TAG_VALUE}"
    done

    [[ ! -z "${dateList[@]+x}" ]] && echo "REM DATE ${dateList[0]}}"
    [[ ! -z "${composerList[@]+x}" ]] && echo "PERFORMER \"${composerList[0]}}\""
    [[ ! -z "${conductorList[@]+x}" ]] && echo "REM CONDUCTOR \"${conductorList[0]}\""
    [[ ! -z "${orchestraList[@]+x}" ]] && echo "REM ORCHESTRA \"${orchestraList[0]}\""
    [[ ! -z "${artistLust[@]+x}" ]] && echo "PERFORMER \"${artistList[0]}\""
    [[ ! -z "${albumList[@]+x}" ]] && echo "TITLE \"${albumList[0]}\""
    echo "FILE \"${imageidList[0]}.flac\" WAVE"
    local COUNT=0
    while [[ ${COUNT} -lt ${#breakList[@]} ]]; do
        [[ ${COUNT} -le 8 ]] && local TRACK_NO="0$(( ${COUNT} + 1 ))" || local TRACK_NO="$(( ${COUNT} + 1 ))"
        echo "  TRACK ${TRACK_NO} AUDIO" 
        echo "    TITLE \"${trackList[${COUNT}]}\""
        echo "    INDEX 01 ${breakList[${COUNT}]}"
        local COUNT=$(( ${COUNT} + 1 ))
    done
    return 0
}

