#!/bin/bash

###
# Returns true if IMAGEID is not excluded from the OPT_EXCLUDE_FILE.
###

is_not_excluded() {
    local IMAGEID="${1}"
    local EXCLUDE="${2}"
    local excludeList=($(cat ${EXCLUDE}))

    [[ -z ${excludeList[@]} ]] && return 0

    for exclude in ${excludeList[@]}; do
        local FIELD=$(echo ${exclude} | cut -d'=' -f1)
        local VALUE=$(echo ${exclude} | cut -d'=' -f2)
        [[ -z "$(grep -i -l "\"${FIELD}\" : \"${VALUE}\"" ${IMAGEID}.tags)" ]] || return 1
    done
    return 0
}

