#!/bin/bash

# doc is_selected {
#
# DESCRIPTION
#   is selected - Returns true if IMAGEID is defined as selected in DB_FILE.
#
# USAGE
#   is_selected </path/to/db/file> <IMAGEID> <TRACKID>
#
#  }

is_selected() {
    local DB_FILE="${1}"
    local IMAGEID="${2}"
    local TRACKID="${3}"
    
    [[ "$(awk -v imageid=${IMAGEID} -v trackid=${TRACKID} 'BEGIN{FS"\t"}{if($2==imageid && $3==trackid){print $1}}' ${DB_FILE})"  == "true" ]] && return 0 || return 1
}

