#!/bin/bash

# doc print_future_meta {
#
# DESCRIPTION
#   print_future_meta - Prints metadata of specified TRACKNUMBER, from textfile following 
#   the MTAG specification. Outputs as standard FIELD=VALUE that can then be pipped into
#   metaflac.
#
# USAGE
#   print_future_meta </path/to/mtag/file> <track no>
#
# }


print_future_meta() {
    local MTAG=${1}
    local TRACKNUMBER="${2}"
    local tagList=($(awk 'BEGIN{RS="\",*\n * \"";FS="\" : \""}{if($1!~"@"){print $1}}' ${MTAG} | awk '!seen[$0]++'))

    for tag in ${tagList[@]}; do
        echo -n "${tag}=$(print_meta_field ${MTAG} ${TRACKNUMBER} ${tag});"
    done
    echo -n "IMAGEID=$(sed 's|.tags||g' <<< $(basename "${MTAG}"))"
}

