#!/bin/bash

# doc print_meta_flac {
#
# DESCRIPTION
#   print_meta_flac - Prints metadata of remote flac in FIELD=VALUE; format.
#
# USAGE
#   print_meta_flac </path/to/flac> [<field_1> <field_2> <...>]
#
# }

print_meta_flac() {
    local fileList=(${@})

    for file in ${fileList[@]}; do
        [[ ! -f ${file} ]] && return 1
    
        local METADATA=$(awk 'BEGIN{FS="]: ";ORS=";"}{if($1 ~ /comment\[/){print $2}}' <<< $(metaflac --list --block-type=VORBIS_COMMENT "${file}"))
        echo ${METADATA} | sed 's|.$||'
    done
} 
