#!/bin/bash

# doc print_future_meta {
#
# DESCRIPTION
#   print_future_meta - Prints metadata of specified TRACKNUMBER, from textfile following 
#   the MTAG specification. Outputs as standard FIELD=VALUE that can then be pipped into
#   metaflac.
#
# USAGE
#   print_future_meta </path/to/mtag/file> <track no>
#
# }


print_future_meta() {
    local MTAG=${1}
    local TRACKNUMBER="${2}"
    local tagList=($(awk 'BEGIN{RS="\",*\n * \"";FS="\" : \""}{if($1!~"@"){print $1}}' ${MTAG} | awk '!seen[$0]++'))

    for tag in ${tagList[@]}; do
        local COUNT=1
        while [[ ${COUNT} -le ${TRACKNUMBER} ]]; do
            local PRTVAR=$(print_meta_field ${MTAG} ${COUNT} ${tag})
            [[ ! -z ${PRTVAR} ]] && local CURVAR=${PRTVAR}
            local COUNT=$(( ${COUNT} + 1 ))
        done
        echo -n "${tag}=${CURVAR};"
        unset CURVAR
        unset PRTVAR
    done
    echo -n "IMAGEID=$(sed 's|.tags||g' <<< $(basename "${MTAG}"))"
}

