#!/bin/bash

###
# Prints VALUE of FIELD, for specific TRACK NUMBER out of a JSON string. Expects to be used
# by print_meta()
###

print_meta_field() {
    local TRACK_NO="${1}"
    local FIELD="${2}"; shift 2
    local TAGS="${@}"

    awk -v track="${TRACK_NO}" 'BEGIN {RS="\" * }"}{if(NR==track){print $0}}' <<< ${TAGS} | awk -v field="${FIELD}" 'BEGIN {RS="\", ";FS="\" : \"";}{if($1==field){print $2}}'
}
