#!/bin/bash

# doc print_meta_field {
#
# DESCRIPTION
#   print_meta_field - Prints VALUE of FIELD, for specific TRACK NUMBER out of a JSON string. Expects to be used
#   by print_meta()
#
# USAGE
#   print_meta_field <file> <track_no> <field_name>
#
# }

print_meta_field() {
    local FILE="${1}"
    local TRACK_NO="${2}"
    local FIELD="${3}"

    awk -v track="${TRACK_NO}" 'BEGIN {RS="\"\n * }"}{if(NR==track){print $0}}' ${FILE} |   awk -v field="${FIELD}" 'BEGIN{RS="\",*\n * \"";FS="\" : \""}{if($1==field){print $2}}'
}
