#!/bin/bash

# doc print_mtag_trackno {
#
# DESCRIPTION
#   print_mtag_trackno - Prints track number of TRACKID using MTAG file
#
# USAGE
#   print_mtag_trackno <path/to/git/dir> <IMAGEID> <TRACKID>
#
# }

print_mtag_trackno() {
    local GIT_DIR="${1}"
    local IMAGEID="${2}"
    local TRACKID="${3}"

    local TOTALTRACKS=$(grep \"@\" ${GIT_DIR}/${IMAGEID}.tags | wc -l)

    local COUNT=1
    while [[ ${COUNT} -le ${TOTALTRACKS} ]]; do    
        [[ "$(print_mtag_field ${GIT_DIR}/${IMAGEID}.tags ${COUNT} TRACKID)" == "${TRACKID}" ]] && echo ${COUNT}
        local COUNT=$(( ${COUNT} + 1 ))
    done
}

