#!/bin/bash

###
# Prints output dir based on provided metadata TAGS. Expects input from print_meta function.
###

print_target_dir() {
    local TAGS="${@}"
    local tagList=(GENRE COMPOSER ALBUM ARTIST PERFORMER DATE DISCNUMBER TOTALDISCS TRACKNUMBER TITLE)

    for tag in ${tagList[@]}; do
        CURTAG="$(awk -v field=${tag} 'BEGIN{RS=";";FS="="}{if($1==field){printf $2}}' <<< ${TAGS})"
        eval local ${tag}='${CURTAG}'
    done

    if [[ "${GENRE}" == "Classical" ]]; then
        echo -n "${GENRE}/${COMPOSER}/${ALBUM}/${ARTIST}/${DATE} - ${PERFORMER}/"
    else
        echo -n "${GENRE}/${ARTIST}/${DATE} - ${ALBUM}/"  
    fi
    [[ ${TOTALDISCS} -gt 1 ]] && echo -n "${DISCNUMBER}."
    printf "%02d" ${TRACKNUMBER}
    echo -n " - $(sed 's|/|-|g' <<< ${TITLE} | sed 's|?||g')"
}

