#!/bin/bash

# doc print_present_path {
#
# DESCRIPTION
#   Prints path of exiting TRACKID.
#
# USAGE
#   print_present_path </path/to/db/file> <trackid>
#
# }

print_present_path() {
    local DB_FILE="${1}"
    local TRACKID="${2}"

    awk -v trackid=${TRACKID} 'BEGIN{FS="\t"}{if($3==trackid){print $4}}' ${DB_FILE}
} 
