#!/bin/bash

# doc print_present_path {
#
# DESCRIPTION
#   Prints path of exiting TRACKID.
#
# USAGE
#   print_present_path </path/to/db/file> <trackid>
#
# }

print_present_path() {
    local DB_FILE="${1}"
    local IMAGEID="${2}"
    local TRACKID="${3}"

    awk -v imageid=${IMAGEID} -v trackid=${TRACKID} 'BEGIN{FS="\t"}{if($2==imageid && $3==trackid){print $4}}' ${DB_FILE}
} 
