#!/bin/bash

# doc print_present_meta {
#
# DESCRIPTION
#   print_present_meta - Prints metadata of remote flac in FIELD=VALUE; format.
#
# USAGE
#   print_present_meta </path/to/flac
#
# }

print_present_meta() {
    local FILE="${1}"
    
    if [[ -f ${FILE} ]]; then
         awk 'BEGIN{FS=": ";ORS=";"}{if($1 ~ /comment\[/){print $2}}' <<< $(metaflac --list --block-type=VORBIS_COMMENT "${FILE}") | sed 's|.$||'  

    fi
} 
