#!/bin/bash

###
# Splits specified FLAC image into multiple flac files using a text file formatted under the
# CUE specification
###

split_flac() {
    local FLAC="${1}"
    local CUE="${2}"

    [[ -z "$(cuebreakpoints ${CUE} 2>/dev/null)" ]] && { cat ${FLAC} > split-track01.flac; return 0; }
    cuebreakpoints ${CUE} 2>/dev/null | shntool split ${FLAC} -o flac -O always
    [[ $? -ne 0 ]] && { cuebreakpoints ${CUE} 2>/dev/null | sed s/$/0/ |  shntool split ${FLAC} -o flac -O always; return 2; } || return 0
}

