#!/bin/bash

# doc update_db {
#
# DESCRIPTION
#   update_db - Updates TARGET's DB_FILE with defined IMAGEIDs
#
# USAGE
#   update_db <path/to/git/dir> <path/to/target/dir> <path/to/db/file> <IMAGEID> <...>
#
# }

update_db() {
    local GIT_DIR="${1}"
    local TARGET="${2}"
    local DB_FILE="${3}"; shift 3
    local imageidList=(${@})

    [[ -f "${DB_FILE}" ]] || touch "${DB_FILE}"
    for imageid in ${imageidList[@]}; do
        trackidList=($(awk 'BEGIN{FS="\" : \"";RS="\",\n * \""}{if($1=="TRACKID"){print $2}}' ${GIT_DIR}/${imageid}.tags))
        for trackid in ${trackidList[@]}; do
            if [[ -z $(awk -v imageid="${imageid}" -v trackid="${trackid}" 'BEGIN{FS="\t"}{if($2==imageid && $3==trackid){print $0}}' ${DB_FILE}) ]]; then
                _msg ECHO "Adding ${trackid} of ${imageid} to database file"
                echo -e "true\t${imageid}\t${trackid}\tnull" >> ${DB_FILE}
            fi
        done
    done
    return 0
}
